services:
  postgres:
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
  user-service:
    build: ./user-service
    ports:
      - 8090:8090
    depends_on:
      - postgres
  product-service:
    build: ./product-service
    ports:
      - 8091:8091
    depends_on:
      - postgres
      - user-service
  order-service:
    build: ./order-service
    ports:
      - 8092:8092
    depends_on:
      - postgres
      - user-service
      - product-service
      - rabbitmq
  payment-service:
    build: ./payment-service
    depends_on:
      - postgres
      - rabbitmq

volumes:
  postgres_data:
    driver: local
